"""Pydantic schemas for AI Threat Advisory Reasoning and Explainability."""
from datetime import datetime, timezone
from enum import Enum
from typing import Any
import uuid

from pydantic import BaseModel, Field, field_validator


class ThreatSeverity(str, Enum):
    INFORMATIONAL = "INFORMATIONAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AdvisoryAction(str, Enum):
    ALLOW = "ALLOW"
    MONITOR = "MONITOR"
    ALERT = "ALERT"
    BLOCK_RECOMMENDED = "BLOCK_RECOMMENDED"
    QUARANTINE_RECOMMENDED = "QUARANTINE_RECOMMENDED"


class MITRETechnique(BaseModel):
    technique_id: str = Field(description="MITRE ATT&CK ID, e.g. T1071.001")
    technique_name: str = Field(description="Human readable name of the technique")
    tactic: str = Field(description="Associated tactic, e.g. Command and Control")
    reference_url: str = Field(default="", description="URL to MITRE ATT&CK documentation")


class ThreatEvidence(BaseModel):
    source: str = Field(description="Signal origin: e.g. 'z_score_baseline', 'reputation', 'anomaly_forest'")
    metric_name: str = Field(description="Name of the metric evaluated")
    observed_value: Any = Field(description="Observed value during inference")
    threshold_or_baseline: Any = Field(default=None, description="Expected normal baseline or trigger threshold")
    anomaly_contribution: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weight of this evidence in the final risk score (0.0 - 1.0)",
    )


class ThreatAdvisory(BaseModel):
    advisory_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    process_name: str = Field(description="Binary or process name under evaluation")
    process_id: int | None = Field(default=None, description="Operating system PID if known")
    destination_ip: str | None = Field(default=None, description="Target remote IP address")
    destination_port: int | None = Field(default=None, description="Target remote port")
    protocol: str = Field(default="TCP", description="Network protocol")

    severity: ThreatSeverity = Field(description="Assessed threat severity rating")
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Model confidence in this assessment (0.0 to 1.0)",
    )
    recommended_action: AdvisoryAction = Field(
        description="Recommended policy action (Advisory only)",
    )

    summary: str = Field(
        description="Concise 1-2 sentence threat assessment summary for SOC/User",
    )
    detailed_reasoning: str = Field(
        description="Detailed analytical breakdown of telemetry, z-scores, and behavioral risk",
    )
    mitre_mappings: list[MITRETechnique] = Field(
        default_factory=list,
        description="Relevant MITRE ATT&CK tactics and techniques",
    )
    evidence: list[ThreatEvidence] = Field(
        default_factory=list,
        description="Key telemetry and statistical anomalies supporting the advisory",
    )

    provider_name: str = Field(description="AI provider that produced this advisory")
    inference_latency_ms: float = Field(ge=0.0, description="Latency of advisory generation in milliseconds")
    is_fallback: bool = Field(default=False, description="True if generated by local fallback engine")
    is_advisory_only: bool = Field(
        default=True,
        frozen=True,
        description="Safety invariant: always True to guarantee advisory isolation",
    )

    @field_validator("is_advisory_only")
    @classmethod
    def validate_advisory_isolation(cls, v: bool) -> bool:
        if not v:
            raise ValueError("Safety guardrail violation: is_advisory_only must always be True.")
        return v
