import os
from pathlib import Path

files = {}

# 1. backend/ai/__init__.py
files['backend/ai/__init__.py'] = '''"""AI Threat Advisory Reasoning and Routing Module."""
from backend.ai.router import AIRouter
from backend.ai.schemas import (
    AdvisoryAction,
    MITRETechnique,
    ThreatAdvisory,
    ThreatEvidence,
    ThreatSeverity,
)

__all__ = [
    "AIRouter",
    "ThreatAdvisory",
    "ThreatSeverity",
    "AdvisoryAction",
    "MITRETechnique",
    "ThreatEvidence",
]
'''

# 2. backend/ai/schemas.py
files['backend/ai/schemas.py'] = '''"""Pydantic schemas for AI Threat Advisory Reasoning and Explainability."""
from datetime import datetime, timezone
from enum import Enum
from typing import Any
import uuid

from pydantic import BaseModel, Field, field_validator


class ThreatSeverity(str, Enum):
    INFORMATIONAL = "INFORMATIONAL"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AdvisoryAction(str, Enum):
    ALLOW = "ALLOW"
    MONITOR = "MONITOR"
    ALERT = "ALERT"
    BLOCK_RECOMMENDED = "BLOCK_RECOMMENDED"
    QUARANTINE_RECOMMENDED = "QUARANTINE_RECOMMENDED"


class MITRETechnique(BaseModel):
    technique_id: str = Field(description="MITRE ATT&CK ID, e.g. T1071.001")
    technique_name: str = Field(description="Human readable name of the technique")
    tactic: str = Field(description="Associated tactic, e.g. Command and Control")
    reference_url: str = Field(default="", description="URL to MITRE ATT&CK documentation")


class ThreatEvidence(BaseModel):
    source: str = Field(description="Signal origin: e.g. 'z_score_baseline', 'reputation', 'anomaly_forest'")
    metric_name: str = Field(description="Name of the metric evaluated")
    observed_value: Any = Field(description="Observed value during inference")
    threshold_or_baseline: Any = Field(default=None, description="Expected normal baseline or trigger threshold")
    anomaly_contribution: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Weight of this evidence in the final risk score (0.0 - 1.0)",
    )


class ThreatAdvisory(BaseModel):
    advisory_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    process_name: str = Field(description="Binary or process name under evaluation")
    process_id: int | None = Field(default=None, description="Operating system PID if known")
    destination_ip: str | None = Field(default=None, description="Target remote IP address")
    destination_port: int | None = Field(default=None, description="Target remote port")
    protocol: str = Field(default="TCP", description="Network protocol")

    severity: ThreatSeverity = Field(description="Assessed threat severity rating")
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Model confidence in this assessment (0.0 to 1.0)",
    )
    recommended_action: AdvisoryAction = Field(
        description="Recommended policy action (Advisory only)",
    )

    summary: str = Field(
        description="Concise 1-2 sentence threat assessment summary for SOC/User",
    )
    detailed_reasoning: str = Field(
        description="Detailed analytical breakdown of telemetry, z-scores, and behavioral risk",
    )
    mitre_mappings: list[MITRETechnique] = Field(
        default_factory=list,
        description="Relevant MITRE ATT&CK tactics and techniques",
    )
    evidence: list[ThreatEvidence] = Field(
        default_factory=list,
        description="Key telemetry and statistical anomalies supporting the advisory",
    )

    provider_name: str = Field(description="AI provider that produced this advisory")
    inference_latency_ms: float = Field(ge=0.0, description="Latency of advisory generation in milliseconds")
    is_fallback: bool = Field(default=False, description="True if generated by local fallback engine")
    is_advisory_only: bool = Field(
        default=True,
        frozen=True,
        description="Safety invariant: always True to guarantee advisory isolation",
    )

    @field_validator("is_advisory_only")
    @classmethod
    def validate_advisory_isolation(cls, v: bool) -> bool:
        if not v:
            raise ValueError("Safety guardrail violation: is_advisory_only must always be True.")
        return v
'''

# 3. backend/ai/prompts.py
files['backend/ai/prompts.py'] = '''"""System prompts and extraction templates for AI Threat Advisory Reasoning."""
import json

SYSTEM_THREAT_ANALYST_PROMPT = """You are Sentinel AI, an expert autonomous firewall security analyst and threat reasoning engine.
Your task is to analyze network telemetry, statistical baseline z-scores, and process intelligence to produce structured advisory risk ratings.

### Operational Guardrails:
1. Ground your reasoning ONLY on provided telemetry, statistical deviations (Z-Scores >= 3.0), reputation scores, and process attributes.
2. If evidence is ambiguous, assign lower confidence and recommend MONITOR rather than BLOCK_RECOMMENDED.
3. You produce purely advisory analysis. You do NOT have execution authority.
4. Always output strictly valid JSON matching the ThreatAdvisory schema.
"""


def build_analysis_prompt(context: dict) -> str:
    serialized = json.dumps(context, indent=2, default=str)
    return (
        "Please analyze the following network event and behavioral telemetry payload:\\n\\n"
        f"{serialized}\\n\\n"
        "Respond with ONLY a valid JSON object matching the ThreatAdvisory schema."
    )
'''

# 4. backend/ai/providers/__init__.py
files['backend/ai/providers/__init__.py'] = '''"""AI Providers Package."""
from backend.ai.providers.base import BaseAIProvider, ProviderHealth, ProviderStatus
from backend.ai.providers.gemini_provider import GeminiFlashProvider
from backend.ai.providers.local_fallback import LocalFallbackProvider

__all__ = [
    "BaseAIProvider",
    "ProviderHealth",
    "ProviderStatus",
    "GeminiFlashProvider",
    "LocalFallbackProvider",
]
'''

# 5. backend/ai/providers/base.py
files['backend/ai/providers/base.py'] = '''"""Abstract Base Provider for AI Threat Reasoning."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Any

from backend.ai.schemas import ThreatAdvisory


class ProviderStatus(str, Enum):
    ONLINE = "ONLINE"
    DEGRADED = "DEGRADED"
    OFFLINE = "OFFLINE"
    UNCONFIGURED = "UNCONFIGURED"


@dataclass
class ProviderHealth:
    provider_name: str
    status: ProviderStatus
    latency_ms: float | None = None
    message: str = "Operational"


class BaseAIProvider(ABC):
    @property
    @abstractmethod
    def provider_name(self) -> str:
        pass

    @abstractmethod
    async def health_check(self) -> ProviderHealth:
        pass

    @abstractmethod
    async def generate_advisory(self, context: dict[str, Any]) -> ThreatAdvisory:
        pass
'''

# 6. backend/ai/providers/gemini_provider.py
files['backend/ai/providers/gemini_provider.py'] = '''"""Google Gemini 2.5 Flash Provider for online structured threat reasoning."""
import json
import logging
import os
import time
from typing import Any
import httpx

from backend.ai.prompts import SYSTEM_THREAT_ANALYST_PROMPT, build_analysis_prompt
from backend.ai.providers.base import BaseAIProvider, ProviderHealth, ProviderStatus
from backend.ai.schemas import ThreatAdvisory

logger = logging.getLogger(__name__)


class GeminiFlashProvider(BaseAIProvider):
    def __init__(
        self,
        api_key: str | None = None,
        model: str = "gemini-2.5-flash",
        timeout_sec: float = 3.0,
    ) -> None:
        self.api_key = api_key or os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
        self.model = model
        self.timeout_sec = timeout_sec
        self._endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"

    @property
    def provider_name(self) -> str:
        return f"gemini:{self.model}"

    def is_configured(self) -> bool:
        return bool(self.api_key and not self.api_key.startswith("test-placeholder"))

    async def health_check(self) -> ProviderHealth:
        if not self.is_configured():
            return ProviderHealth(
                provider_name=self.provider_name,
                status=ProviderStatus.UNCONFIGURED,
                message="GEMINI_API_KEY not configured",
            )
        start = time.perf_counter()
        try:
            async with httpx.AsyncClient(timeout=self.timeout_sec) as client:
                url = f"{self._endpoint}?key={self.api_key}"
                payload = {
                    "contents": [{"parts": [{"text": "Health check: respond with 'OK'"}]}],
                    "generationConfig": {"maxOutputTokens": 5},
                }
                resp = await client.post(url, json=payload)
                elapsed_ms = (time.perf_counter() - start) * 1000
                if resp.status_code == 200:
                    return ProviderHealth(
                        provider_name=self.provider_name,
                        status=ProviderStatus.ONLINE,
                        latency_ms=round(elapsed_ms, 2),
                    )
                return ProviderHealth(
                    provider_name=self.provider_name,
                    status=ProviderStatus.DEGRADED,
                    latency_ms=round(elapsed_ms, 2),
                    message=f"HTTP {resp.status_code}: {resp.text[:100]}",
                )
        except Exception as exc:
            elapsed_ms = (time.perf_counter() - start) * 1000
            return ProviderHealth(
                provider_name=self.provider_name,
                status=ProviderStatus.OFFLINE,
                latency_ms=round(elapsed_ms, 2),
                message=str(exc),
            )

    async def generate_advisory(self, context: dict[str, Any]) -> ThreatAdvisory:
        if not self.is_configured():
            raise RuntimeError("Gemini API key is not configured.")

        start = time.perf_counter()
        prompt_text = build_analysis_prompt(context)

        request_body = {
            "system_instruction": {
                "parts": [{"text": SYSTEM_THREAT_ANALYST_PROMPT}]
            },
            "contents": [
                {
                    "role": "user",
                    "parts": [{"text": prompt_text}],
                }
            ],
            "generationConfig": {
                "responseMimeType": "application/json",
                "temperature": 0.1,
            },
        }

        async with httpx.AsyncClient(timeout=self.timeout_sec) as client:
            url = f"{self._endpoint}?key={self.api_key}"
            resp = await client.post(url, json=request_body)
            elapsed_ms = (time.perf_counter() - start) * 1000

            if resp.status_code != 200:
                raise RuntimeError(
                    f"Gemini API error (status {resp.status_code}): {resp.text}"
                )

            data = resp.json()
            try:
                candidate = data["candidates"][0]["content"]["parts"][0]["text"]
                parsed = json.loads(candidate)
            except (KeyError, IndexError, json.JSONDecodeError) as exc:
                raise ValueError(f"Failed to parse structured JSON from Gemini response: {exc}")

            parsed["process_name"] = context.get("process_name", "unknown.exe")
            parsed["process_id"] = context.get("process_id")
            parsed["destination_ip"] = context.get("destination_ip")
            parsed["destination_port"] = context.get("destination_port")
            parsed["protocol"] = context.get("protocol", "TCP")
            parsed["provider_name"] = self.provider_name
            parsed["inference_latency_ms"] = round(elapsed_ms, 2)
            parsed["is_fallback"] = False
            parsed["is_advisory_only"] = True

            return ThreatAdvisory.model_validate(parsed)
'''

# 7. backend/ai/providers/local_fallback.py
files['backend/ai/providers/local_fallback.py'] = '''"""Local Fallback Provider for offline resilience and deterministic threat reasoning."""
import time
from typing import Any

from backend.ai.providers.base import BaseAIProvider, ProviderHealth, ProviderStatus
from backend.ai.schemas import (
    AdvisoryAction,
    MITRETechnique,
    ThreatAdvisory,
    ThreatEvidence,
    ThreatSeverity,
)


class LocalFallbackProvider(BaseAIProvider):
    @property
    def provider_name(self) -> str:
        return "local-heuristic:deterministic-v1"

    async def health_check(self) -> ProviderHealth:
        return ProviderHealth(
            provider_name=self.provider_name,
            status=ProviderStatus.ONLINE,
            latency_ms=0.1,
            message="Local fallback engine ready",
        )

    async def generate_advisory(self, context: dict[str, Any]) -> ThreatAdvisory:
        start = time.perf_counter()

        fusion_score = float(context.get("fusion_risk_score", 0.0))
        anomaly_score = float(context.get("anomaly_score", 0.0))
        max_z_score = float(context.get("max_z_score", 0.0))
        reputation_score = float(context.get("reputation_score", 0.0))
        findings = context.get("behavior_findings", [])
        process_name = context.get("process_name", "unknown.exe")
        dest_ip = context.get("destination_ip")
        dest_port = context.get("destination_port")
        protocol = context.get("protocol", "TCP")

        evidence: list[ThreatEvidence] = []
        mitre_mappings: list[MITRETechnique] = []

        if max_z_score >= 3.0:
            evidence.append(
                ThreatEvidence(
                    source="baseline_z_score",
                    metric_name="max_behavioral_z_score",
                    observed_value=round(max_z_score, 2),
                    threshold_or_baseline=3.0,
                    anomaly_contribution=min(1.0, max_z_score / 10.0),
                )
            )

        if anomaly_score > 0.5:
            evidence.append(
                ThreatEvidence(
                    source="anomaly_forest",
                    metric_name="isolation_forest_score",
                    observed_value=round(anomaly_score, 3),
                    threshold_or_baseline=0.5,
                    anomaly_contribution=anomaly_score,
                )
            )

        for finding in findings:
            finding_str = str(finding)
            evidence.append(
                ThreatEvidence(
                    source="rule_engine",
                    metric_name="behavior_finding",
                    observed_value=finding_str,
                    anomaly_contribution=0.7,
                )
            )
            if "BEACON" in finding_str.upper():
                mitre_mappings.append(
                    MITRETechnique(
                        technique_id="T1071.001",
                        technique_name="Web Protocols: Regular C2 Beaconing",
                        tactic="Command and Control",
                        reference_url="https://attack.mitre.org/techniques/T1071/001/",
                    )
                )
            elif "PORT_SCAN" in finding_str.upper() or "EXPLOSION" in finding_str.upper():
                mitre_mappings.append(
                    MITRETechnique(
                        technique_id="T1046",
                        technique_name="Network Service Discovery",
                        tactic="Discovery",
                        reference_url="https://attack.mitre.org/techniques/T1046/",
                    )
                )

        if fusion_score >= 80.0 or max_z_score >= 6.0:
            severity = ThreatSeverity.CRITICAL
            recommended_action = AdvisoryAction.BLOCK_RECOMMENDED
            confidence = 0.92
            summary = f"Critical behavioral anomaly detected for {process_name} exhibiting extreme baseline deviation."
        elif fusion_score >= 60.0 or max_z_score >= 4.0:
            severity = ThreatSeverity.HIGH
            recommended_action = AdvisoryAction.BLOCK_RECOMMENDED
            confidence = 0.85
            summary = f"High threat probability for {process_name} connecting to {dest_ip}:{dest_port}."
        elif fusion_score >= 35.0 or max_z_score >= 3.0:
            severity = ThreatSeverity.MEDIUM
            recommended_action = AdvisoryAction.ALERT
            confidence = 0.75
            summary = f"Suspicious network pattern identified for {process_name}. Elevated risk score {fusion_score:.1f}."
        elif fusion_score >= 15.0:
            severity = ThreatSeverity.LOW
            recommended_action = AdvisoryAction.MONITOR
            confidence = 0.70
            summary = f"Minor statistical divergence observed for {process_name}; continued monitoring recommended."
        else:
            severity = ThreatSeverity.INFORMATIONAL
            recommended_action = AdvisoryAction.ALLOW
            confidence = 0.95
            summary = f"Routine network activity for {process_name} within expected parameters."

        detailed_reasoning = (
            f"Deterministic offline analysis evaluated process '{process_name}' "
            f"targeting {dest_ip}:{dest_port} ({protocol}). "
            f"Metrics: RiskFusion={fusion_score:.1f}/100, AnomalyScore={anomaly_score:.2f}, "
            f"MaxZScore={max_z_score:.2f}, Reputation={reputation_score:.1f}."
        )

        elapsed_ms = (time.perf_counter() - start) * 1000

        return ThreatAdvisory(
            process_name=process_name,
            process_id=context.get("process_id"),
            destination_ip=dest_ip,
            destination_port=dest_port,
            protocol=protocol,
            severity=severity,
            confidence_score=confidence,
            recommended_action=recommended_action,
            summary=summary,
            detailed_reasoning=detailed_reasoning,
            mitre_mappings=mitre_mappings,
            evidence=evidence,
            provider_name=self.provider_name,
            inference_latency_ms=round(elapsed_ms, 2),
            is_fallback=True,
            is_advisory_only=True,
        )
'''

# 8. backend/ai/router.py
files['backend/ai/router.py'] = '''"""AIRouter: Multi-provider orchestration, timeout guardrails, and advisory isolation."""
import asyncio
import logging
import time
from typing import Any

from backend.ai.providers.base import BaseAIProvider, ProviderHealth, ProviderStatus
from backend.ai.providers.gemini_provider import GeminiFlashProvider
from backend.ai.providers.local_fallback import LocalFallbackProvider
from backend.ai.schemas import ThreatAdvisory

logger = logging.getLogger(__name__)


class AIRouter:
    def __init__(
        self,
        primary_provider: BaseAIProvider | None = None,
        fallback_provider: BaseAIProvider | None = None,
        default_timeout_sec: float = 3.0,
    ) -> None:
        self.primary_provider = primary_provider or GeminiFlashProvider(timeout_sec=default_timeout_sec)
        self.fallback_provider = fallback_provider or LocalFallbackProvider()
        self.default_timeout_sec = default_timeout_sec

    async def get_providers_health(self) -> dict[str, ProviderHealth]:
        tasks = [
            self.primary_provider.health_check(),
            self.fallback_provider.health_check(),
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        health_map = {}
        for provider, res in zip([self.primary_provider, self.fallback_provider], results):
            if isinstance(res, Exception):
                health_map[provider.provider_name] = ProviderHealth(
                    provider_name=provider.provider_name,
                    status=ProviderStatus.OFFLINE,
                    message=str(res),
                )
            else:
                health_map[provider.provider_name] = res
        return health_map

    async def analyze_threat(
        self,
        context: dict[str, Any],
        timeout_sec: float | None = None,
        force_fallback: bool = False,
    ) -> ThreatAdvisory:
        timeout = timeout_sec or self.default_timeout_sec

        if not force_fallback:
            try:
                advisory = await asyncio.wait_for(
                    self.primary_provider.generate_advisory(context),
                    timeout=timeout,
                )
                logger.info(
                    "Generated threat advisory via primary provider: %s (Severity: %s)",
                    self.primary_provider.provider_name,
                    advisory.severity,
                )
                return advisory
            except asyncio.TimeoutError:
                logger.warning(
                    "Primary AI provider %s timed out after %.2fs; activating local fallback.",
                    self.primary_provider.provider_name,
                    timeout,
                )
            except Exception as exc:
                logger.warning(
                    "Primary AI provider %s failed (%s); activating local fallback.",
                    self.primary_provider.provider_name,
                    exc,
                )

        fallback_advisory = await self.fallback_provider.generate_advisory(context)
        logger.info(
            "Generated threat advisory via fallback provider: %s (Severity: %s)",
            self.fallback_provider.provider_name,
            fallback_advisory.severity,
        )
        return fallback_advisory
'''

# 9. tests/unit/ai/__init__.py
files['tests/unit/ai/__init__.py'] = ''

# 10. tests/unit/ai/test_ai_router.py
files['tests/unit/ai/test_ai_router.py'] = '''"""Unit tests for AI Schemas, Providers, and AIRouter orchestration."""
import asyncio
import json
from unittest.mock import AsyncMock, patch
import pytest
import httpx

from backend.ai.providers.base import ProviderStatus
from backend.ai.providers.gemini_provider import GeminiFlashProvider
from backend.ai.providers.local_fallback import LocalFallbackProvider
from backend.ai.router import AIRouter
from backend.ai.schemas import (
    AdvisoryAction,
    MITRETechnique,
    ThreatAdvisory,
    ThreatEvidence,
    ThreatSeverity,
)


def test_threat_advisory_schema_defaults_and_validation():
    advisory = ThreatAdvisory(
        process_name="svchost.exe",
        destination_ip="1.1.1.1",
        destination_port=443,
        severity=ThreatSeverity.LOW,
        confidence_score=0.9,
        recommended_action=AdvisoryAction.ALLOW,
        summary="Standard HTTPS connection.",
        detailed_reasoning="Normal behavioral baseline observed.",
        provider_name="test-provider",
        inference_latency_ms=12.5,
    )
    assert advisory.is_advisory_only is True
    assert advisory.severity == ThreatSeverity.LOW
    assert len(advisory.advisory_id) > 0


def test_threat_advisory_guardrail_invariant():
    with pytest.raises(ValueError, match="Safety guardrail violation"):
        ThreatAdvisory(
            process_name="malware.exe",
            severity=ThreatSeverity.CRITICAL,
            confidence_score=1.0,
            recommended_action=AdvisoryAction.BLOCK_RECOMMENDED,
            summary="Attack detected",
            detailed_reasoning="Malicious payload",
            provider_name="test",
            inference_latency_ms=1.0,
            is_advisory_only=False,
        )


@pytest.mark.anyio
async def test_local_fallback_provider_heuristic_critical():
    provider = LocalFallbackProvider()
    context = {
        "process_name": "mimikatz.exe",
        "process_id": 9999,
        "destination_ip": "185.220.101.5",
        "destination_port": 4444,
        "protocol": "TCP",
        "fusion_risk_score": 88.5,
        "max_z_score": 7.2,
        "anomaly_score": 0.85,
        "behavior_findings": ["BEACON_DETECTED_INTERVAL_2S"],
    }

    advisory = await provider.generate_advisory(context)
    assert advisory.severity == ThreatSeverity.CRITICAL
    assert advisory.recommended_action == AdvisoryAction.BLOCK_RECOMMENDED
    assert advisory.is_fallback is True
    assert any(m.technique_id == "T1071.001" for m in advisory.mitre_mappings)
    assert len(advisory.evidence) >= 2


@pytest.mark.anyio
async def test_local_fallback_provider_heuristic_informational():
    provider = LocalFallbackProvider()
    context = {
        "process_name": "chrome.exe",
        "process_id": 1234,
        "destination_ip": "142.250.190.46",
        "destination_port": 443,
        "fusion_risk_score": 5.0,
        "max_z_score": 0.4,
    }
    advisory = await provider.generate_advisory(context)
    assert advisory.severity == ThreatSeverity.INFORMATIONAL
    assert advisory.recommended_action == AdvisoryAction.ALLOW


@pytest.mark.anyio
async def test_gemini_flash_provider_mocked_success():
    provider = GeminiFlashProvider(api_key="valid-test-key")

    mock_gemini_payload = {
        "candidates": [
            {
                "content": {
                    "parts": [
                        {
                            "text": json.dumps({
                                "severity": "HIGH",
                                "confidence_score": 0.94,
                                "recommended_action": "BLOCK_RECOMMENDED",
                                "summary": "Unusual outbound beacon detected from PowerShell.",
                                "detailed_reasoning": "Connection frequency is 5 standard deviations above baseline.",
                                "mitre_mappings": [
                                    {
                                        "technique_id": "T1059.001",
                                        "technique_name": "PowerShell",
                                        "tactic": "Execution",
                                        "reference_url": "https://attack.mitre.org/techniques/T1059/001/"
                                    }
                                ],
                                "evidence": [
                                    {
                                        "source": "baseline_z_score",
                                        "metric_name": "frequency",
                                        "observed_value": 5.2,
                                        "threshold_or_baseline": 3.0,
                                        "anomaly_contribution": 0.8
                                    }
                                ]
                            })
                        }
                    ]
                }
            }
        ]
    }

    mock_resp = httpx.Response(status_code=200, json=mock_gemini_payload, request=httpx.Request("POST", "http://test"))

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value = mock_resp
        context = {
            "process_name": "powershell.exe",
            "destination_ip": "198.51.100.1",
            "destination_port": 8443,
        }
        advisory = await provider.generate_advisory(context)
        assert advisory.severity == ThreatSeverity.HIGH
        assert advisory.recommended_action == AdvisoryAction.BLOCK_RECOMMENDED
        assert advisory.is_fallback is False
        assert advisory.provider_name.startswith("gemini:")


@pytest.mark.anyio
async def test_ai_router_automatic_fallback_on_gemini_timeout():
    gemini_mock = AsyncMock(spec=GeminiFlashProvider)
    gemini_mock.provider_name = "gemini:gemini-2.5-flash"

    async def _hang(*args, **kwargs):
        await asyncio.sleep(2.0)

    gemini_mock.generate_advisory.side_effect = _hang

    router = AIRouter(primary_provider=gemini_mock, default_timeout_sec=0.1)

    context = {
        "process_name": "test_app.exe",
        "fusion_risk_score": 75.0,
        "max_z_score": 4.5,
    }

    advisory = await router.analyze_threat(context)
    assert advisory is not None
    assert advisory.is_fallback is True
    assert advisory.severity in (ThreatSeverity.HIGH, ThreatSeverity.CRITICAL)


@pytest.mark.anyio
async def test_ai_router_health_checks():
    router = AIRouter()
    health_map = await router.get_providers_health()
    assert "local-heuristic:deterministic-v1" in health_map
    assert health_map["local-heuristic:deterministic-v1"].status == ProviderStatus.ONLINE
'''

for rel_path, content in files.items():
    p = Path(rel_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding='utf-8')
    print(f'Successfully wrote: {rel_path}')
